### ISSUE TITLE
Delete dialog ambiguity

### ISSUE THREAD

**Issue by magnusviri** [jamf/JamfSync#11]
I know what you guys mean with the delete dialog but I thought I'd give some more feedback. The delete dialog says "Are you sure you want to delete the N selected items?" The options are, "Files and associated packages," "Files only" and "Cancel". Because "Files" is an option I must assume that "associated packages" means the Jamf records. I would assume that "associated packages" meant files and not a database records.

I'm glad the interface still indicates which files are missing on the server, since that is one of the main reasons I use the tool, to delete the database records that are missing files.

**Comment by HarryStrandJamf** [comment]
Your assumption is correct that by "associated packages" that I mean the package records on the server. I agree with you that it's a little ambiguous, but I'm not sure what wording would be less ambiguous and not confusing. I did fix an issue where it wasn't working to delete the associated packages unless it was a "Cloud" distribution point. That will be in the next release. If you have ideas for better wording, I'll consider them.

**Comment by Maclife420** [comment]
Ok can you please be more precise what exactly is the difference. Files only will delete the selected files on the dp. But what exactly happens when you select files and associated files? What is the recommended way?

**Comment by HarryStrandJamf** [comment]
It's possible to have multiple distribution points, each with different files. If we automatically deleted the package records in Jamf Pro when deleting a file from a distribution point, that could cause policies that use files from a different distribution point to fail since there would no longer be a package record for that file. Deleting just the file is the safer option, however, if you know there are no policies that reference any of the files that will be deleted, then selecting "Delete files and associated packages" would be the recommended way to go.

**Comment by Maclife420** [comment]
thanks for the clarification

**Comment by HarryStrandJamf** [comment]
Closing this as not planned since I'm not sure how to make it more clear without too much text in the selection item.

**Comment by magnusviri** [comment]
Sorry, I was slow to reply.

Instead of "associated files" can you say "associated records"? People might not know what a record is but at least they wont immediately confuse it with files and will probably jump to the correct meaning, which is that it's something to do with the web interface.

**Comment by HarryStrandJamf** [comment]
It currently says "Files and associated packages". So maybe "Files and associated package records"?

**Comment by HarryStrandJamf** [comment]
Reopening so I can take care of this with the next release. Especially if I get confirmation on my proposed wording.

**Comment by HarryStrandJamf** [comment]
This was implemented in version 1.3.3

**Comment by magnusviri** [comment]
Is there a release date for 1.3.3? The releases page lists 1.3.2 as the latest.

**Comment by HarryStrandJamf** [comment]
I'm sorry...I changed this quite a while ago and I thought it was released already. As of yet there isn't a planned release date. I'm hoping to get a couple of the more important tasks completed first, but the time to focus on them is pretty hard to come by lately.
