### ISSUE TITLE
Can't delete Jamf database records for packages

### ISSUE THREAD

**Issue by magnusviri** [jamf/JamfSync#12]
I can't delete Jamf database records for packages. I hope this isn't by design because there is no easy way in the Jamf interface to see which packages don't have files.

So I guess this explains why none of the options in the delete dialog refer to just deleting the Jamf database record.

**Comment by magnusviri** [comment]
![Screenshot 2024-05-28 at 11 10 32 AM](https://github.com/jamf/JamfSync/assets/711269/cd1c6817-923a-4085-abee-79dc1999e582)

**Comment by HarryStrandJamf** [comment]
I fixed this and it will be available in the next release.

**Comment by HarryStrandJamf** [comment]
Closing this since it was fixed with version 1.3.1
