### ISSUE TITLE
Jamf Sync modifying Package Settings

### ISSUE THREAD

**Issue by joxpUB** [jamf/JamfSync#13]
During or after Jamf Sync runs, it appears to have edited a package to disable Fill User Templates and Fill existing users.

This was a sync from JCDS to a file share, the only edit recorded by Jamf Change Management logs to the package is by our Jamf Sync service account.

Package creation settings:
![image](https://github.com/jamf/JamfSync/assets/40008990/2e60d330-ceb5-45e6-8a15-c5498d44e99f)

Package edited by our Jamf Sync service account:
![image](https://github.com/jamf/JamfSync/assets/40008990/c2978b60-ff83-4fd2-bc55-da4cd177ce82)

Anecdotally I've heard that it has edited someone's package priorities as well.

**Comment by joxpUB** [comment]
Here's a Jamf Sync log that may or may not be relevant. This was gathered on a subsequent sync days later:

2024-05-30 16:08:31.347 Jamf Sync[87572:656208] jsonData = 
{"priority":10,"categoryId":"-1","packageName":"Install EndNote 21.app.zip","suppressEula":false,"uninstall":false,"fillUserTemplate":false,"osInstall":false,"fileName":"Install EndNote 21.app.zip","rebootRequired":false,"size":"120743182","suppressUpdates":false,"suppressFromDock":false,"suppressRegistration":false,"md5":"c1e692289ce1ba18367037a10b2a1a25"}
24/05/30 16:08:31-ERROR: Failed to transmit data for https://[org].jamfcloud.com/api/v1/packages. Status code: 400
24/05/30 16:08:31-ERROR: Failed to copy Install EndNote 21.app.zip to Campus File Share ([org]): dataRequestFailed(statusCode: 400, message: Optional("{\n  \"httpStatus\" : 400,\n  \"errors\" : [ {\n    \"code\" : \"DUPLICATE_FIELD\",\n    \"description\" : \"duplicate name\",\n    \"id\" : null,\n    \"field\" : \"fileName\"\n  } ]\n}"))

**Comment by HarryStrandJamf** [comment]
I figured out what was happening with this and fixed it. It will be available in the next release.

**Comment by HarryStrandJamf** [comment]
Closing this issue since it was fixed with version 1.3.1.
