### ISSUE TITLE
Application Crashes

### ISSUE THREAD

**Issue by mrmte** [jamf/JamfSync#19]
Im selecting JCDS as the source and Destination is a cloud RHEL server. It asks for the password BUT NOT the username. The application just crashes. The application should also be asking for the username as simply providing a password will not work!

**Comment by HarryStrandJamf** [comment]
Could you make it crash and then go to Console (hit CMD-SPACE, type "Console" and hit Enter), then select crash reports or the left, find the latest Jamf Sync crash report, right click it, Show in Finder, and then attach that report here so I can get some clues about where the problem in the code is? Also, please attach a screen shot of Jamf Sync showing the selected source and destination folder before the crash.

**Comment by mrmte** [comment]
must have been a one off, its working now

**Comment by HarryStrandJamf** [comment]
Thanks for the update! If it happens again, please attach a crash report and screen shots. But hopefully it will never happen again!
