### ISSUE TITLE
Defender interferes with sync from Cloud DP to local SMB DP

### ISSUE THREAD

**Issue by david-london** [jamf/JamfSync#24]
I get transfer interruption failures when Defender is installed.  What is the location of temporary files while transferring from cloud DP to local SMB DP so I can exclude them from Defender?

**Comment by HarryStrandJamf** [comment]
Sorry for the delay. It uses NSTemporaryDirectory to create a temporary directory. This is usually something like "/var/folders/7t/f8lrg4c174j_m8cxdwgg27x00000gp/T/", and I think the only part of that which is consistent is "/var/folders".

**Comment by HarryStrandJamf** [comment]
I'm closing this for now since It think the only ask here is where it stores temporary files.
