### ISSUE TITLE
UNSUPPORTED_FILE_TYPE

### ISSUE THREAD

**Issue by jfiliceatcsumb** [jamf/JamfSync#25]
JamfSync 1.3.2 attempts to sync unsupported file types. We have pdf files under the eBooks section of our JCDS cloud distribution point, which JamfSync attempts to copy but fails every time.  I would like to filter out or exclude some file type extensions from sync.

`24/08/02 17:35:51-ERROR: Failed to copy 508_02.pdf to JSSfileshare on MyJamfProServer: dataRequestFailed(statusCode: 400, message: Optional("{\n  \"httpStatus\" : 400,\n  \"errors\" : [ {\n    \"code\" : \"UNSUPPORTED_FILE_TYPE\",\n    \"description\" : \"Unsupported file extension. Acceptable formats are pkg, mpkg, dmg or zip.\",\n    \"id\" : \"0\",\n    \"field\" : \"fileName\"\n  } ]\n}"))
`

**Comment by HarryStrandJamf** [comment]
This should be fixed with version 1.3.3.
