### ISSUE TITLE
notes removed on sync

### ISSUE THREAD

**Issue by rickgmac** [jamf/JamfSync#29]
When syncing from CDP to File Server.
If there are notes for the package. They get removed.

This is a screen shot of a package with notes before JamfSync
<img width="1938" alt="Screen Shot 2024-08-21 at 4 59 54 pm" src="https://github.com/user-attachments/assets/710bd86e-01a6-459d-8b7d-fde7cc2518dd">

Then this is a screen shot of the same package after Jamf sync has run using api client. You can see username as the api client ID
<img width="2254" alt="Screen Shot 2024-08-21 at 5 03 38 pm" src="https://github.com/user-attachments/assets/a9e56c0e-55e6-44b0-ae35-74344c5ef468">

**Comment by HarryStrandJamf** [comment]
Do you know what version of Jamf Sync was used when that was synchronized? I thought a change made in version 1.3.1 should have solved that.

**Comment by HarryStrandJamf** [comment]
I'm going to close this as resolved for now, but if you can duplicate the issue with the latest version, please let me know.
